---
subtitle: "Een analyse van kansengelijkheid in studiesucces (retentie na 1 jaar)"

## Auteur en datum
author: "Theo Bakker, lector Learning Technology & Analytics, De HHs"
date: last-modified

## LTA Template
ltatemplate: 0.9.1.9000

## Parameters        
params:
  versie: "1.0"
  succes: "Retentie na 1 jaar"
  propedeusediploma: "Nvt" ## Nvt/Met P/Zonder P
  
  ## Recreate plots
  recreateplots: true
  
  ## BRV:ORM DT
  faculteit: "BRV"
  opleidingsnaam: "B Bestuurskunde Overheidsmanagement"
  opleiding: "BO"
  opleidingsvorm: "duaal"
  opleidingsvorm_afkorting: "DU"
  selectie: false
  
  ## Author
  author: "Theo Bakker, lector Learning Technology & Analytics"
  
## Content
includes:
  inleiding:      true
  data:           true
  model_lr:       true
  model_rf:       true
  model_svm:      false
  final_fit:      true
  conclusies:     true
  verantwoording: true
  nextsteps:      true
  copyright:      true
---

# Inleiding {.unnumbered}

```{r setup, include = FALSE}
#| label: setup
#| echo: false

## Sluit het _Setup.R bestand in
source("_Setup.R")
```

<!-- Inleiding -->

## Onderzoek naar kansengelijkheid - No Fairness without Awareness

Het lectoraat Learning Technology & Analytics (LTA) van De Haagse Hogeschool heeft tot doel kansengelijkheid voor studenten ter verhogen met behulp van learning analytics en inzet van learning technology. 

Het lectoraat werkt aan een methode om te kunnen analyseren of er sprake is van bias in de studiedata in relatie tot het succes van studenten en van een gebrek aan kansengelijkheid. Voor deze methode zetten we prognosemodellen in die we ontwikkelen met machine learning. Een prognosemodel is dus niet een doel op zich, maar het instrument voor een fairness analyse. Zie voor een verdere toelichting op het onderzoeksprogramma: '[No Fairness without Awareness](https://www.dehaagsehogeschool.nl/onderzoek/kenniscentra/no-fairness-without-awareness)'. 

## Het nut van prognosemodellen

Prognosemodellen kunnen inzicht bieden in de factoren die gecorreleerd zijn aan de uitval of - als tegenhanger - de **retentie** van studenten. Met deze inzichten kan een opleiding interventies ontwikkelen om uitval te verminderen of te voorkomen en retentie te bevorderen. Voor de uitleg van de toepassing van deze methode om kansengelijkheid op te sporen is retentie beter te volgen dan uitval. Vandaar dat we in deze analyse de retentie na 1 jaar als uitkomstvariabele nemen.

## Toepassing 

<!-- ## BRV:ORM DT -->
<!--   faculteit: "BRV" -->
<!--   opleidingsnaam: "B Bestuurskunde Overheidsmanagement" -->
<!--   opleiding: "BO" -->
<!--   opleidingsvorm: "duaal" -->
<!--   opleidingsvorm_afkorting: "DU" -->

In deze analyse passen we de methode toe op de opleiding `r params$faculteit` \| **`r params$opleidingsnaam`** (`r params$opleiding`), `r params$opleidingsvorm`, eerstejaars - **`r sSucces_model`**

::: {.callout-warning appearance="default" icon="true"}
## Disclaimer

De modellen die we in deze analyses ontwikkelen zijn bedoeld om de dynamiek in het studiesucces van studenten een opleiding beter te begrijpen om kansengelijkheid te bevorderen.

**Deze modellen mogen op geen enkele wijze gebruikt worden om individuele studenten te beoordelen of hun succes te voorspellen.**
:::

## Opbouw analyse en aanpak

Deze analyse kent drie hoofdstukken met de drie stappen van de aanpak: 

- **Hoofdstuk 1: Prognosemodel retentie na 1 jaar** - De ontwikkeling van een aantal prognosemodellen om retentie na 1 jaar te voorspellen, waaruit het best presterende model wordt gekozen.
- **Hoofdstuk 2: Factoranalyse** - Een verdiepende analyse op de factoren van het best presterende model.
- **Hoofdstuk 3: Kansengelijkheid** - De analyse van de modellen op bias en kansengelijkheid.

## Vragen of suggesties

Heb je vragen of suggesties over deze analyse? Neem dan contact op met Theo Bakker via 06-25637172 of per mail via [t.c.bakker@hhs.nl](mailto:t.c.bakker@hhs.nl). 
